//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Inventory.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Inventory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap circled_user_male_skin_type_3_512px {
            get {
                object obj = ResourceManager.GetObject("circled_user_male_skin_type_3_512px", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ثبت با موفقیت انجام گردید..
        /// </summary>
        public static string Complete_Operation {
            get {
                return ResourceManager.GetString("Complete_Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap error_512 {
            get {
                object obj = ResourceManager.GetObject("error-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی مالی کافی نیست. لطفا بررسی شود..
        /// </summary>
        public static string Financial_Error {
            get {
                return ResourceManager.GetString("Financial_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap hide_512 {
            get {
                object obj = ResourceManager.GetObject("hide-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap info_512 {
            get {
                object obj = ResourceManager.GetObject("info_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دریافت مقدار نامعتبر.
        /// </summary>
        public static string Invalid_Value {
            get {
                return ResourceManager.GetString("Invalid_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کالای ثبت شده در انبار موجود می باشد..
        /// </summary>
        public static string Inventory_Error {
            get {
                return ResourceManager.GetString("Inventory_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap new_user_1080_Light_Gray {
            get {
                object obj = ResourceManager.GetObject("new_user_1080_Light_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقص در علمیات ثبت.
        /// </summary>
        public static string Operation_Defect {
            get {
                return ResourceManager.GetString("Operation_Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خریدی صورت نگرفته. حداقل یک خرید ثبت نمایید..
        /// </summary>
        public static string Purchase_Error {
            get {
                return ResourceManager.GetString("Purchase_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فروشی صورت نگرفته. حداقل یک فروش ثبت نمایید..
        /// </summary>
        public static string Sales_Error {
            get {
                return ResourceManager.GetString("Sales_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سرویس انجام شد..
        /// </summary>
        public static string Service_Register {
            get {
                return ResourceManager.GetString("Service_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سرویس انجام نگردید.
        /// </summary>
        public static string Service_Register_Error {
            get {
                return ResourceManager.GetString("Service_Register_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap show_512 {
            get {
                object obj = ResourceManager.GetObject("show-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap succes_512 {
            get {
                object obj = ResourceManager.GetObject("succes-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tik_False {
            get {
                object obj = ResourceManager.GetObject("Tik False", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tik_True {
            get {
                object obj = ResourceManager.GetObject("Tik True", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap user_512 {
            get {
                object obj = ResourceManager.GetObject("user_512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap warning_512 {
            get {
                object obj = ResourceManager.GetObject("warning-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
